CREATE TABLE Account (
     Id              int GENERATED BY DEFAULT AS IDENTITY,
     AccountTypeId      tinyint NOT NULL,
     Email           varchar(255) NOT NULL,
     Username        varchar(16) NOT NULL,
     PasswordSalt    varchar(32) NOT NULL,
     PasswordHash    varchar(44) NOT NULL,
     CreationDate    timestamp NOT NULL,
     LastActiveDate  timestamp NOT NULL,
     ProfileImageUrl varchar(255) DEFAULT 'default-profile-image' NOT NULL,
     Title           varchar(32) DEFAULT 'Member' NOT NULL,
     Location        varchar(32) DEFAULT 'The Internet' NOT NULL,
     CONSTRAINT PK_Account_Id
         PRIMARY KEY (Id),
     CONSTRAINT UK_Account_Email
         UNIQUE (Email),
     CONSTRAINT UK_Account_Username
         UNIQUE (Username));

CREATE TABLE Board (
    Id          tinyint GENERATED BY DEFAULT AS IDENTITY,
    SectionId   tinyint NOT NULL,
    Title       varchar(32) NOT NULL,
    Description varchar(128),
    Weight      int DEFAULT 0 NOT NULL,
    Closed      boolean DEFAULT 'FALSE' NOT NULL,
    CONSTRAINT PK_Board_Id
       PRIMARY KEY (Id));

CREATE TABLE Media (
    Id             int GENERATED BY DEFAULT AS IDENTITY,
    MediaTypeId    tinyint NOT NULL,
    Title          varchar(255) NOT NULL,
    PosterImageUrl varchar(255) DEFAULT 'default-poster-image' NOT NULL,
    Episodes       int,
    Runtime        int,
    AiredStartDate timestamp,
    AiredEndDate   timestamp,
    CONSTRAINT PK_Media_Id
       PRIMARY KEY (Id));

CREATE TABLE MediaType (
    Id   tinyint GENERATED BY DEFAULT AS IDENTITY,
    Name varchar(16),
    CONSTRAINT PK_MediaType_Id
       PRIMARY KEY (Id));

CREATE TABLE Post (
    Id                  int GENERATED BY DEFAULT AS IDENTITY,
    ThreadId            int,
    ParentId            int,
    OwnerAccountId      int,
    LastEditorAccountId int DEFAULT null,
    CreationDate        timestamp NOT NULL,
    LastEditDate        timestamp DEFAULT null,
    CONSTRAINT PK_Post_Id
      PRIMARY KEY (Id));

CREATE TABLE PostContent (
    PostId  int NOT NULL,
    Content clob,
    CONSTRAINT PK_PostDetails_PostId
        PRIMARY KEY (PostId));

CREATE TABLE Section (
    Id     tinyint GENERATED BY DEFAULT AS IDENTITY,
    Title  varchar(32) NOT NULL,
    Weight int DEFAULT 0 NOT NULL,
    CONSTRAINT PK_Section_Id
        PRIMARY KEY (Id));

CREATE TABLE StreamingMedia (
    MediaId int NOT NULL,
    CONSTRAINT PK_StreamingMedia_MediaId
        PRIMARY KEY (MediaId));

CREATE TABLE Thread (
    Id             int GENERATED BY DEFAULT AS IDENTITY,
    BoardId        tinyint,
    OwnerAccountId int,
    MediaId        int,
    CreationDate   timestamp NOT NULL,
    ClosedDate     timestamp,
    Title          varchar(64) NOT NULL,
    ViewCount      int DEFAULT 0 NOT NULL,
    CONSTRAINT PK_Thread_Id
        PRIMARY KEY (Id),
    CONSTRAINT CK_Thread_NotNegativeViewCount
        CHECK (ViewCount >= 0));

CREATE TABLE AccountType (
    Id   tinyint GENERATED BY DEFAULT AS IDENTITY,
    Name varchar(32),
    CONSTRAINT PK_AccountType_Id
      PRIMARY KEY (Id));

CREATE TABLE Vote (
    PostId       int NOT NULL,
    AccountId    int NOT NULL,
    VoteType     tinyint NOT NULL,
    CreationDate timestamp DEFAULT '0' NOT NULL,
    CONSTRAINT PK_Vote_PostId_AccountId
      PRIMARY KEY (PostId,
                   AccountId));